---

basic_utilities:
  - htop
  - curl
  - unzip
  - zip
  - wget
  - xclip
  - powerline
  - fonts-powerline
  - silversearcher-ag
  - build-essential
  - libssl-dev
  - libreadline-dev
  - zlib1g-dev
  - aspell
  - imagemagick
  - vim
  - fd-find
  - ripgrep
  - software-properties-common
  - libtool-bin
  - cmake

everyday_apps:
  - signal-desktop
  - discord
  - zoom-client
  - chromium

uncouth_everyday_apps:
  - slack
